=== LaAlpacaLoca/24_25-LEMA-PROYECTOXML-ZUGAZA/xsd/el_jardin_de_la_alpaca_sch1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="tienda">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="iva" type="xs:string" />
                <xs:element name="servicios">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="servicio" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="TipoNombre" maxOccurs="1" />
                                        <xs:element name="precio">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="TipoPrecio">
                                                        <xs:attribute name="moneda" type="TipoMoneda" default="yen"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="ganancia" type="xs:string" />
                                        <xs:element name="imagen" type="xs:string" />
                                        <xs:element name="enlace" type="xs:string" />
                                        <xs:element name="descuento" type="xs:string" />
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:ID" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="productos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="producto" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="TipoNombre" maxOccurs="1"/>
                                        <xs:element name="precio">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="moneda" type="TipoMoneda" default="yen" />
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="ganancia" type="xs:string" />
                                        <xs:element name="marca" type="xs:string" />
                                        <xs:element name="imagen" type="xs:string" />
                                        <xs:element name="stock" type="xs:string" />
                                        <xs:element name="enlace" type="xs:string" />
                                        <xs:element name="descuento" type="xs:string" />
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:ID" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <!-- RESTRICIONES-->
    <xs:simpleType name="TipoPrecio">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="0"></xs:minInclusive>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="TipoMoneda">
        <xs:restriction base="xs:string">
            <xs:enumeration value="yen"></xs:enumeration>
            <xs:enumeration value="usd"></xs:enumeration>
            <xs:enumeration value="euro"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="TipoNombre">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z][A-Za-zZáéíóúñÑ0-9() ]*"></xs:pattern>
            <xs:minLength value="4"></xs:minLength>
        </xs:restriction>


    </xs:simpleType>



</xs:schema>

=== LaAlpacaLoca/24_25-LEMA-PROYECTOXML-ZUGAZA/xsd/el_jardin_de_la_alpaca.xml
<tienda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="el_jardin_de_la_alpaca_sch1.xsd">
	<iva>10</iva>
    <servicios>
     <!-- Lista de servicios ofrecidos en la tienda -->
        <servicio id="s001">
            <nombre>Chequeo medico de alpacas</nombre>
            <precio moneda="yen">5000</precio>
            <ganancia>3000</ganancia>
            <imagen>../imagenes/medico.jpg</imagen>
            <enlace>https://veterinariosurbion.com/caso-clinico/revision-a-alpacas/</enlace>
            <descuento>28</descuento>
        </servicio>
        <servicio id="s002">
            <nombre>Corte de pelo y esquilado de alpacas</nombre>
            <precio moneda="yen">3000</precio>
            <ganancia>2000</ganancia>
            <imagen>../imagenes/esquila_de_alpaca.jpg</imagen>
            <enlace>https://www.youtube.com/watch?v=vQE4wDUpeH0</enlace>
            <descuento>1</descuento>
        </servicio>
        <servicio id="s003">
            <nombre>Alimentaci√≥n de alpacas</nombre>
            <precio moneda="yen">12000</precio>
            <ganancia>1300</ganancia>
            <imagen>../imagenes/alimentacion_alpaca.jpg</imagen>
            <enlace>https://www.youtube.com/watch?v=1HqVUJYgth0</enlace>
            <descuento>0</descuento>
        </servicio>
    </servicios>

    <productos>
        <producto id="p001">
            <nombre>Paquete heno para alpacas 5kg</nombre>
            <!-- Este producto es alimento para alpacas, el stock es bastante alto. -->
            <precio moneda="yen">13000</precio>
            <ganancia>10000</ganancia>
            <marca>Rodrigo milanuncios</marca>
            <imagen>../imagenes/heno.jpg</imagen>
            <stock>37855</stock>
            <enlace>www.milanuncios.com/alimentacion-animales/alpacas-de-heno-528127065.htm</enlace>
            <descuento>0</descuento>
        </producto>

        <producto id="p002">
            <nombre>Champu para alpacas</nombre>
            <precio moneda="yen">20000</precio>
            <ganancia>0</ganancia>
            <marca>Pet Prince</marca>
            <imagen>../imagenes/champu_para_alpacas.jpg</imagen>
            <stock>63</stock>
            <enlace>www.amazon.com/-/es/Prince-Champ%C3%BA-totalmente-natural-31-9oz/dp/B078M56398</enlace>
            <descuento>0</descuento>
        </producto>

        <producto id="p003">
            <nombre>Peluche de Alpaca en Lana de Alpaca Natural (23cm)</nombre>
            <precio moneda="yen">14520</precio>
            <ganancia>1000</ganancia>
            <marca>Inkari</marca>
            <imagen>../imagenes/peluche_alpaca.jpg</imagen>
            <stock>69</stock>
            <enlace>www.amazon.es/Inkari-Alpaca-Super-Fluffy-Sustainable/dp/B07Y8TVYXG/ref=sr_1_7?dib=eyJ2IjoiMSJ9</enlace>
            <descuento>0</descuento>
        </producto>

        <producto id="p004">
            <nombre>Chal de piel de alpaca</nombre>
            <precio moneda="yen">10020</precio>
            <ganancia>4000</ganancia>
            <marca>artesanal</marca>
            <imagen>../imagenes/chal.webp</imagen>
            <stock>130</stock>
            <enlace>alpacasdelatierruca.es/alpacas-de-cantabria-portfolio-servicios/chal-de-alpaca-100-tejido-en-telar/</enlace>
            <descuento>5</descuento>
        </producto>
    </productos>
</tienda>
    <!-- Fin del documento XML -->
